x-mysql-template: &mysql-template
  image: mysql:latest
  env_file:
    - .env.local
  healthcheck:
    test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    interval: 20s
    timeout: 10s
    retries: 3

services:
  spring:
    container_name: service-payment
    build:
      context: .
    env_file:
      - .env.local
    ports:
      - "8080:8080"

  mysql:
    <<: *mysql-template
    hostname: dev
    container_name: mysql-dev
    ports:
      - "3306:3306"
