x-mysql-template: &mysql-template
  image: mysql:latest
  healthcheck:
    test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    interval: 20s
    timeout: 10s
    retries: 3

name: service-payment
services:
  spring:
    container_name: service-payment
    image: oomia/service-payment:latest
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    <<: *mysql-template
    hostname: mysql
    container_name: mysql
    expose:
      - "3306"

networks:
  private-subnet: # private: 172.19.0.x
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
