#
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
#

# this is a global configuration file
# no options are overridden here

# Core configuration
spring.application.name: spring-web-jpa-concurrency
spring.profiles.active: default, dev, init-sql

# Database configuration
spring.datasource:
  url: jdbc:mysql://${MYSQL_SERVER}:3306/${MYSQL_DATABASE}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
