#
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
#

# this is a global configuration file
# no options are overridden here

# Core configuration
spring.application.name: spring-web-jpa-concurrency
spring.profiles.active: default, dev

## Swagger configuration
springdoc:
  swagger-ui.path: /
  show-actuator: false

# Database configuration
spring.datasource:
  url: jdbc:mysql://${MYSQL_SERVER:localhost}:3306/${MYSQL_DATABASE:mydatabase}
  username: ${MYSQL_USER:myuser}
  password: ${MYSQL_PASSWORD:secret}
  driver-class-name: com.mysql.cj.jdbc.Driver


