#
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
#

# this is a global configuration file
# no options are overridden here

# Core configuration
spring.application.name: spring-web-jpa-concurrency
spring.profiles:
  default: default
  active: dev

## Swagger configuration
springdoc:
  swagger-ui.path: /
  show-actuator: true

# Database configuration
spring.datasource:
  url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:payment}
  username: ${MYSQL_USER:payment}
  password: ${MYSQL_PASSWORD:payment}
  driver-class-name: com.mysql.cj.jdbc.Driver
