name: Run gradlew clean test on main

on:
  pull_request:
    branches:
      - main

jobs:
  build_test_and_coverage:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gradlew clean test on main
        run: ./gradlew clean test

      - name: Upload test coverage to Codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          fail_ci_if_error: true
          verbose: true
          flags: 'integration'
