name: Run gradlew test on Ubuntu and MacOS

on:
  pull_request:
    branches:
      - develop
      - feature/**

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'gradle'

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*gradle*') }}
          restore-keys: gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gradlew test
        run: ./gradlew test --warning-mode=all

      - name: Upload test coverage to Codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          fail_ci_if_error: true
          verbose: true
          flags: ${{ github.ref == 'refs/pull/develop' && 'integration' || 'unittests' }}

  build_and_test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'gradle'

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*gradle*') }}
          restore-keys: gradle-


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gradlew test
        run: ./gradlew test --warning-mode=all
